// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPHjTUoTaRN2v5pahxgdQp8gDEVjSU4jU',
    appId: '1:415943577729:web:eacc256202c6cbd214fd80',
    messagingSenderId: '415943577729',
    projectId: 'cicdezpz',
    authDomain: 'cicdezpz.firebaseapp.com',
    storageBucket: 'cicdezpz.firebasestorage.app',
    measurementId: 'G-M0BWYZ27XR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ1t35TC5iw4tnKptG1gSzXROtUoX_3AY',
    appId: '1:415943577729:android:5cbb5f4f31e9c27b14fd80',
    messagingSenderId: '415943577729',
    projectId: 'cicdezpz',
    storageBucket: 'cicdezpz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm_CnuTcHQttTbfXd9TxCR37bbFjnMmkU',
    appId: '1:415943577729:ios:c61dbe3ab94e93f714fd80',
    messagingSenderId: '415943577729',
    projectId: 'cicdezpz',
    storageBucket: 'cicdezpz.firebasestorage.app',
    iosBundleId: 'com.cicdezpz.cicdezpz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm_CnuTcHQttTbfXd9TxCR37bbFjnMmkU',
    appId: '1:415943577729:ios:c61dbe3ab94e93f714fd80',
    messagingSenderId: '415943577729',
    projectId: 'cicdezpz',
    storageBucket: 'cicdezpz.firebasestorage.app',
    iosBundleId: 'com.cicdezpz.cicdezpz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPHjTUoTaRN2v5pahxgdQp8gDEVjSU4jU',
    appId: '1:415943577729:web:969bfcf0fd44c4ab14fd80',
    messagingSenderId: '415943577729',
    projectId: 'cicdezpz',
    authDomain: 'cicdezpz.firebaseapp.com',
    storageBucket: 'cicdezpz.firebasestorage.app',
    measurementId: 'G-VP7DFR76MF',
  );
}
